### ISSUE TITLE
ComfyUI Integration with Custom Node Creation Bounty [$3000]

### ISSUE THREAD

**Issue by JJassonn69** [JJassonn69/bounties#6]
To ease the process of onboarding many more creators and enthusiasts, we aim to construct a ComfyUI [custom node](https://docs.comfy.org/essentials/custom_node_overview/) that is tightly integrated with Livepeer network for processing AI workflow commands from [ComfyUI](https://docs.comfy.org/get_started/introduction/) dashboard. Since, many creators 🧑‍🎨 rely on ComfyUI for incorporating open-source models into their workflows, this enhancement would significantly improve user experience and drive adoption. 🚀 

We are calling on the community to implement this important tool to [AI-network](https://docs.livepeer.org/ai/pipelines/overview#models-on-the-ai-subnet/) so that we can empower the creators with the open source, decentralised and cost effective access to the models on the Livepeer Network. Successfully integrating with ComfyUI by creating this custom node will provide opportunity for further utilisation of our [pipelines](https://docs.livepeer.org/ai/pipelines/overview#models-on-the-ai-subnet/) and bolster Livepeer as top network for AI infrastructure. 🔥

---

## Required Skillset

- Strong [Python](https://www.python.org/) and [Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/) programming skills.
- Familiar with [ComfyUI](https://docs.comfy.org/get_started/introduction/) and its workflows.
- Basic background with developing SaaS products.

---

## Bounty Requirements

1. **Implementation:** Develop a working custom node to `ComfyUI` workflows that uses Livepeer AI pipelines for task completion. One should be able to host `ComfyUI` interface and use the custom build node to leverage Livepeer network. Create also a sample workflow that demonstrates the use of the custom node with multiple  pipelines from Livepeer together (e.g. text-to-image and image-to-video) similar to this [example](https://github.com/replicate/comfyui-replicate?tab=readme-ov-file/).
2. **Functionality:** The custom node should provide functionality that pipelines in AI-network are able to handle. It should also be modular such that it also needs to be easily extendable to other pipelines and additional functionalities and features. 
3. **Documentation and Testing:** The bounty will be considered complete with clear documentation for implementation and use. The node should be thoroughly tested across a wide range of use cases to ensure reliability, performance, and real-world applicability, making it user-friendly and encouraging adoption by creators.

---

## Scope Exclusions

- This bounty does **NOT** cover the hosting and providing SaaS product for ComfyUI interface. But can be handled if interested with a separate bounty. 

---

## Implementation Tips

To learn how to create a custom node for `ComfyUI`, refer to their [documentation](https://docs.comfy.org/get_started/introduction/) and explore the examples in their [GitHub repository](https://github.com/comfyanonymous/ComfyUI/). Additionally, be sure to review the Livepeer AI [API Reference documentation](https://docs.livepeer.org/ai/api-reference/text-to-image) for guidance on how to call the Livepeer AI pipelines.

---

## How to Apply

1. **Express Your Interest:** Comment on this issue to indicate your interest and explain why you're the ideal candidate for the task.
2. **Wait for Review:** Our team will review expressions of interest and select the best candidate.
5. **Get Assigned:** If selected, we'll assign the GitHub issue to you.
6. **Start Working:** Dive into your task! If you need assistance or guidance, comment on the issue or join the discussions in the `#developer-lounge` channel on our [Discord server](https://discord.gg/livepeer).
7. **Submit Your Work:** Create a pull request in the relevant repository and request a review.
8. **Notify Us:** Comment on this GitHub issue when your pull request is ready for review.
9. **Receive Your Bounty:** We'll arrange the bounty payment once your pull request is approved.
10. **Gain Recognition:** Your valuable contributions will be showcased in our project's [changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project! 💛

> [!WARNING]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by rickstaa** [comment]
@JJassonn69 thanks! I updated some small things, but now it is good to be posted 🚀.

**Comment by JJassonn69** [comment]
posted to the main bounty repo in livepeer. Closing this issue.
