### ISSUE TITLE
Documentation improvements [retroactive]

### ISSUE THREAD

**Issue by rickstaa** [JJassonn69/bounties#8]
# Overview

To improve the developer experience we want the community to help us apply a suite of improvements to the documentation.

---

## Required Skillset

- Familiarity with [Node JS](https://nodejs.org/en).
- Experience with [Mintlify](https://mintlify.com/).

---

## Bounty Requirements

The bounty hunter should implement the following list of documentation improvements:

- [x] Since we rebranded the AI subnet to the Livepeer AI network all mentions of the AI subnet should be replaced by just Livepeer AI Network in the [Livepeer AI documentation](https://docs.livepeer.org/ai/introduction).
- [x] Since we are now public, remove all **alpha** mentions.
- [ ] Add documentation for the new Segment Anything 2 pipeline (see https://github.com/livepeer/ai-worker/pull/185).
- [ ] Add Orchestrator and Gateway Metrics to documentation under `AI Metrics` under the Gateay and Orchestrator [start-gateway](https://github.com/livepeer/docs/blob/main/ai/gateways/start-gateway.mdx) and [start-orchestrator](https://github.com/livepeer/docs/blob/main/ai/orchestrators/start-orchestrator.mdx) pages. 
    - [ ] The metrics explanation are found [here](https://github.com/livepeer/go-livepeer/pull/3087), [here](https://github.com/livepeer/go-livepeer/pull/3097) and [here](https://github.com/livepeer/go-livepeer/pull/3100).

## Scope Exclusions

---

## Scope Exclusions

---

## Implementation Tips

Please checkout the [Mintlify](https://mintlify.com/docs/quickstart), [NodeJS](https://nodejs.org/en) and [NVM](https://github.com/nvm-sh/nvm) documentation to understand how to update and preview the documentation.

---

## How to Apply

1. **Express Your Interest:** Comment on this issue to indicate your interest and explain why you're the ideal candidate for the task.
2. **Wait for Review:** Our team will review expressions of interest and select the best candidate.
4. **Get Assigned:** If selected, we'll assign the GitHub issue to you.
5. **Start Working:** Dive into your task! If you need assistance or guidance, comment on the issue or join the discussions in the `#developer-lounge` channel on our [Discord server](https://discord.gg/livepeer).
6. **Submit Your Work:** Create a pull request in the relevant repository and request a review.
7. **Notify Us:** Comment on this GitHub issue when your pull request is ready for review.
8. **Receive Your Bounty:** We'll arrange the bounty payment once your pull request is approved.
9. **Gain Recognition:** Your valuable contributions will be showcased in our project's [changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project! 💛

> [!WARNING]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by EAsuperstar** [comment]
I'm Interested in this, I'd like to handle it if you don't mind.

**Comment by EAsuperstar** [comment]
Completed, please review pull request #636

**Comment by EAsuperstar** [comment]
@rickstaa Please could you review my recent [pull request](https://github.com/livepeer/docs/pull/642) with a commit carrying the Orchestrator and Gateway metrics documentation you requested. Thanks.

**Comment by JJassonn69** [comment]
Bounty has successfully completed. Closing it here.
